arch = { packages = [
  "7zip",
  "aarch64-linux-gnu-gcc",
  "acpi",
  "aichat",
  "alsa-utils",
  "amd-ucode",
  "android-tools",
  "arch-install-scripts",
  "archinstall",
  "archlinux-xdg-menu",
  "arduino-cli",
  "aria2",
  "ark",
  "arm-none-eabi-gcc",
  "arm-none-eabi-gdb",
  "arm-none-eabi-newlib",
  "aubio",
  "audacity",
  "bandwhich",
  "base",
  "base-devel",
  "bat",
  "bc",
  "bear",
  "bemenu-wayland",
  "bind",
  "binwalk",
  "breeze",
  "brightnessctl",
  "btop",
  "btrfs-progs",
  "bundletool",
  "cameractrls",
  "ccache",
  "cimg",
  "ckermit",
  "clang",
  "cliphist",
  "cmake",
  "cmatrix",
  "cmus",
  "code",
  "cpio",
  "crosstool-ng",
  "cyme",
  "darkhttpd",
  "dbus-glib",
  "dmenu",
  "dolphin",
  "dtc",
  "dunst",
  "dust",
  "efibootmgr",
  "egl-wayland",
  "exfatprogs",
  "fastfetch",
  "fbgrab",
  "fd",
  "firefox",
  "fish",
  "flatpak",
  "flatpak-kcm",
  {
    name = "foot",
    hooks = {
      after_install = [
        "systemctl",
        "--user",
        "enable",
        "--now",
        "foot-server.socket",
      ]
    }
  },
  "fractal",
  "freecad",
  "fuse2",
  "fzf",
  "gdb",
  "ghidra",
  "ghostscript",
  "gimp",
  "git",
  "git-filter-repo",
  "github-cli",
  "glad",
  "glm",
  "glmark2",
  "gnome-themes-extra",
  "gnuplot",
  "go",
  "gradle",
  "grex",
  "grim",
  "gst-plugin-pipewire",
  "guvcview",
  "helix",
  "htop",
  "hunspell-en_us",
  "hunspell-ru",
  "hyprland",
  "hyprlauncher",
  "hyprlock",
  "hyprpicker",
  "hyprpolkitagent",
  "imagemagick",
  "inetutils",
  "inkscape",
  "inotify-tools",
  "intel-media-driver",
  "inter-font",
  "iotop",
  "iwd",
  "jdk17-openjdk",
  "jdk21-openjdk",
  "jdk8-openjdk",
  "jellyfin-web",
  "just",
  "kate",
  "kdeconnect",
  "kdiskmark",
  "kicad",
  "kicad-library",
  "kicad-library-3d",
  "krita",
  "labwc",
  "less",
  "lib32-gcc-libs",
  "lib32-glibc",
  "lib32-zlib",
  "libpulse",
  "libva-intel-driver",
  "libva-utils",
  "libxcrypt-compat",
  "lilypond",
  "linux",
  "linux-firmware",
  "lmms",
  "lua-language-server",
  "lua-lpeg",
  "luanti",
  "luanti-server",
  "ly",
  "lemurs",
  "lynx",
  "man-db",
  "mangohud",
  "marksman",
  "mercurial",
  "micro",
  "mold",
  "mpv",
  "multipath-tools",
  "mupdf",
  "mupdf-tools",
  "musl",
  "nano",
  "ncdu",
  "neovim",
  "netpbm",
  "networkmanager",
  "nmap",
  "nuspell",
  "nvtop",
  "obs-studio",
  "opencl-mesa",
  "openresolv",
  "openssh",
  "otf-firamath",
  "otf-latinmodern-math",
  "otf-libertinus",
  "pacman-contrib",
  "pandoc-cli",
  "pdf2svg",
  "perl-file-homedir",
  "perl-yaml-tiny",
  "picocom",
  "pipewire",
  "pipewire-alsa",
  "pipewire-jack",
  "pipewire-pulse",
  "pixymon-git",
  "plasma-keyboard",
  "podman",
  "power-profiles-daemon",
  "prismlauncher",
  "pulseview",
  "pypy3",
  "python-cairosvg",
  "python-pip",
  "python-pipx",
  "qbittorrent",
  "qbittorrent-nox",
  "qdl-git",
  "qemu-desktop",
  "qemu-system-arm",
  "qemu-user-static",
  "qemu-user-static-binfmt",
  "qpdf",
  "qt5ct",
  "qt6ct-kde",
  "read-edid",
  "repo",
  "rizin",
  "rsync",
  "ruby",
  "scrcpy",
  "sd",
  "sfml",
  "shfmt",
  "slurp",
  "smartmontools",
  "soundfont-fluid",
  "steam",
  "strace",
  "sway",
  "swayimg",
  "swig",
  "sz",
  "tealdeer",
  "telegram-desktop",
  "tesseract-data-eng",
  "tesseract-data-kaz",
  "tesseract-data-rus",
  "texlab",
  "texlive-binextra",
  "texlive-latexextra",
  "texlive-latexrecommended",
  "time",
  "tinymist",
  "tmux",
  "torbrowser-launcher",
  "torsocks",
  "traceroute",
  "translate-shell",
  "tree",
  "ttf-jetbrains-mono",
  "ttf-jetbrains-mono-nerd",
  "ttf-montserrat",
  "ttf-opensans",
  "typst",
  "typstyle",
  "uboot-tools",
  "ufw",
  "unrar",
  "unrar-free",
  "unzip",
  "uv",
  "virt-manager",
  "vkmark",
  "vulkan-intel",
  "vulkan-nouveau",
  "vulkan-radeon",
  "waybar",
  "wev",
  "wget",
  "whois",
  "wine",
  "wireguard-tools",
  "wireless_tools",
  "wiremix",
  "wireplumber",
  "wireshark-qt",
  "wmenu",
  "xdg-desktop-portal-gtk",
  "xdg-desktop-portal-hyprland",
  "xdg-desktop-portal-wlr",
  "xdg-utils",
  "zathura-pdf-mupdf",
  "zerotier-one",
  "zig",
  "zip",
  "zoxide",
  "zram-generator",
] }
cargo = { packages = [
  { name = "antumbra", options = { version = "1.1.0", git = "https://github.com/shomykohai/penumbra.git", features = [
  ] } },
  { name = "bevy_cli", options = { version = "0.1.0-dev", git = "https://github.com/TheBevyFlock/bevy_cli?branch=main", features = [
  ] } },
  { name = "cargo-binstall", options = { version = "1.21.1", features = [
  ] } },
  { name = "cargo-binutils", options = { version = "0.4.0", features = [
  ] } },
  { name = "cargo-bloat", options = { version = "0.12.1", features = [
  ] } },
  { name = "cargo-cache", options = { version = "0.8.3", features = [
  ] } },
  { name = "cargo-edit", options = { version = "0.13.13", features = [
  ] } },
  { name = "cargo-generate", options = { version = "0.23.14", features = [
  ] } },
  { name = "cargo-merge-driver", options = { version = "0.1.0", git = "https://github.com/relrelb/cargo-merge-driver.git", features = [
  ] } },
  { name = "cargo-ndk", options = { version = "4.1.2", features = [
  ] } },
  { name = "cargo-reedme", options = { version = "0.6.1", features = [
  ] } },
  { name = "cargo-show-asm", options = { version = "0.2.62", features = [
  ] } },
  { name = "cargo-update", options = { version = "22.1.0", features = [
  ] } },
  { name = "cargo-zigbuild", options = { version = "0.23.0", features = [
  ] } },
  { name = "chiptool", options = { version = "0.1.0", git = "https://github.com/embassy-rs/chiptool.git", features = [
  ] } },
  { name = "diffr", options = { version = "0.1.5", features = [
  ] } },
  { name = "difftastic", options = { version = "0.69.0", features = [
  ] } },
  { name = "espflash", options = { version = "4.5.0", features = [
  ] } },
  { name = "form", options = { version = "0.13.0", features = [
  ] } },
  { name = "gh_pkg", options = { version = "0.1.0", features = [
  ] } },
  { name = "license-generator", options = { version = "1.3.0", features = [
  ] } },
  { name = "metapac", options = { version = "0.10.1", features = [
  ] } },
  { name = "nbted", options = { version = "1.5.2", features = [
  ] } },
  { name = "neothesia-cli", options = { version = "0.1.0", git = "https://github.com/PolyMeilex/Neothesia.git", features = [
  ] } },
  { name = "paru", options = { version = "2.1.0", git = "https://github.com/Morganamilo/paru.git", features = [
  ] } },
  { name = "probe-rs-tools", options = { version = "0.32.0", features = [
  ] } },
  { name = "svd2rust", options = { version = "0.37.1", features = [
  ] } },
  { name = "target-gen", options = { version = "0.32.0", features = [
  ] } },
  { name = "wasm-bindgen-cli", options = { version = "0.2.126", features = [
  ] } },
  { name = "wasm-opt", options = { version = "0.116.1", features = [
  ] } },
] }
